<?php

use Illuminate\Database\Seeder;

class BankTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $bank=[
            ['BRI','002'],
            ['EKSPOR INDONESIA','003'],
            ['MANDIRI','008'],
            ['BNI','009'],
            ['DANAMON','011'],
            ['PERMATA BANK','013'],
            ['BCA','014'],
            ['BII','016'],
            ['PANIN','019'],
            ['ARTA NIAGA KENCANA','020'],
            ['NIAGA','022'],
            ['BUANA IND','023'],
            ['LIPPO','026'],
            ['NISP','028'],
            ['AMERICAN EXPRESS BANK LTD','030'],
            ['CITIBANK N.A.','031'],
            ['JP. MORGAN CHASE BANK, N.A.','032'],
            ['OF AMERICA, N.A','033'],
            ['ING INDONESIA BANK','034'],
            ['MULTICOR TBK.','036'],
            ['ARTHA GRAHA','037'],
            ['CREDIT AGRICOLE INDOSUEZ','039'],
            ['THE BANGKOK BANK COMP. LTD','040'],
            ['THE HONGKONG & SHANGHAI B.C.','041'],
            ['THE BANK OF TOKYO MITSUBISHI UFJ LTD','042'],
            ['BANK SUMITOMO MITSUI INDONESIA','045'],
            ['BANK DBS INDONESIA','046'],
            ['BANK RESONA PERDANIA','047'],
            ['BANK MIZUHO INDONESIA','048'],
            ['STANDARD CHARTERED BANK','050'],
            ['BANK ABN AMRO','052'],
            ['BANK KEPPEL TATLEE BUANA','053'],
            ['BANK CAPITAL INDONESIA, TBK.','054'],
            ['BANK BNP PARIBAS INDONESIA','057'],
            ['BANK UOB INDONESIA','058'],
            ['KOREA EXCHANGE BANK DANAMON','059'],
            ['RABOBANK INTERNASIONAL INDONESIA','060'],
            ['ANZ PANIN BANK','061'],
            ['DEUTSCHE BANK AG.','067'],
            ['BANK WOORI INDONESIA','068'],
            ['BANK OF CHINA LIMITED','069'],
            ['BANK BUMI ARTA','076'],
            ['BANK EKONOMI','087'],
            ['BANK ANTARDAERAH','088'],
            ['BANK HAGA','089'],
            ['BANK IFI','093'],
            ['BANK CENTURY, TBK.','095'],
            ['BANK MAYAPADA','097'],
            ['BANK JABAR','110'],
            ['BANK DKI','111'],
            ['BPD DIY','112'],
            ['BANK JATENG','113'],
            ['BANK JATIM','114'],
            ['BPD JAMBI','115'],
            ['BPD ACEH','116'],
            ['BANK SUMUT','117'],
            ['BANK NAGARI','118'],
            ['BANK RIAU','119'],
            ['BANK SUMSEL','120'],
            ['BANK LAMPUNG','121'],
            ['BPD KALSEL','122'],
            ['BPD KALIMANTAN BARAT','123'],
            ['BPD KALTIM','124'],
            ['BPD KALTENG','125'],
            ['BPD SULSEL','126'],
            ['BANK SULUT','127'],
            ['BPD NTB','128'],
            ['BPD BALI','129'],
            ['BANK NTT','130'],
            ['BANK MALUKU','131'],
            ['BPD PAPUA','132'],
            ['BANK BENGKULU','133'],
            ['BPD SULAWESI TENGAH','134'],
            ['BANK SULTRA','135'],
            ['BANK NUSANTARA PARAHYANGAN','145'],
            ['BANK SWADESI','146'],
            ['BANK MUAMALAT','147'],
            ['BANK MESTIKA','151'],
            ['BANK METRO EXPRESS','152'],
            ['BANK SHINTA INDONESIA','153'],
            ['MASPION','157'],
            ['HAGAKITA','159'],
            ['GANESHA','161'],
            ['WINDU KENTJANA','162'],
            ['HALIM INDONESIA BANK','164'],
            ['HARMONI INTERNATIONAL','166'],
            ['KESAWAN','167'],
            ['TABUNGAN NEGARA (PERSERO)','200'],
            ['HIMPUNAN SAUDARA 1906, TBK .','212'],
            ['TABUNGAN PENSIUNAN NASIONAL','213'],
            ['SWAGUNA','405'],
            ['JASA ARTA','422'],
            ['MEGA','426'],
            ['JASA JAKARTA','427'],
            ['BUKOPIN','441'],
            ['SYARIAH MANDIRI','451'],
            ['BISNIS INTERNASIONAL','459'],
            ['SRI PARTHA','466'],
            ['JASA JAKARTA','472'],
            ['BINTANG MANUNGGAL','484'],
            ['BUMIPUTERA','485'],
            ['YUDHA BHAKTI','490'],
            ['MITRANIAGA','491'],
            ['AGRO NIAGA','494'],
            ['INDOMONEX','498'],
            ['ROYAL INDONESIA','501'],
            ['ALFINDO','503'],
            ['SYARIAH MEGA','506'],
            ['INA PERDANA','513'],
            ['HARFA','517'],
            ['PRIMA MASTER BANK','520'],
            ['PERSYARIKATAN INDONESIA','521'],
            ['AKITA','525'],
            ['LIMAN INTERNATIONAL BANK','526'],
            ['ANGLOMAS INTERNASIONAL BANK','531'],
            ['DIPO INTERNATIONAL','523'],
            ['KESEJAHTERAAN EKONOMI','535'],
            ['UIB','536'],
            ['ARTOS IND','542'],
            ['PURBA DANARTA','547'],
            ['BANK MULTI ARTA SENTOSA','548'],
            ['MAYORA','553'],
            ['INDEX SELINDO','555'],
            ['VICTORIA INTERNATIONAL','566'],
            ['EKSEKUTIF','558'],
            ['CENTRATAMA NASIONAL BANK','559'],
            ['FAMA INTERNASIONAL','562'],
            ['SINAR HARAPAN BALI','564'],
            ['HARDA','567'],
            ['FINCONESIA','945'],
            ['MERINCORP','946'],
            ['MAYBANK INDOCORP','947'],
            ['OCBC – INDONESIA','948'],
            ['CHINA TRUST INDONESIA','949'],
            ['COMMONWEALTH','950']
        ];

        foreach ($bank as $i=>$row) {
            \App\Model\Bank::create([
                'nama' => $row[0],
                'kode'=>$row[1]
            ]);
        }


    }
}
